export interface TimelineNode {
  id: string;
  year: string;
  title: string;
  whatHappened: string;
  whyItMattered: string;
}

/**
 * LOCKED. Transcribed verbatim from the Module 1 Content Blueprint,
 * Section 4 (Discovery Timeline Content). Do not add nodes, dates,
 * device names, or figures beyond what is listed there.
 */
export const module1Timeline: TimelineNode[] = [
  {
    id: "eddington",
    year: "1920",
    title: "Eddington",
    whatHappened:
      "British astrophysicist Arthur Eddington proposed that the Sun's energy comes from nuclear processes in its core.",
    whyItMattered:
      "It was the first serious scientific claim that the Sun's power source was nuclear, not chemical — even though the exact mechanism was still unknown.",
  },
  {
    id: "bethe",
    year: "1938–1939",
    title: "Bethe",
    whatHappened:
      "Hans Bethe identified the specific nuclear fusion reactions (the proton-proton chain and CNO cycle) that power stars.",
    whyItMattered:
      "This turned Eddington's proposal into a precise, testable mechanism — the question \"how do stars make energy?\" finally had a real answer.",
  },
  {
    id: "mike",
    year: "1952",
    title: "Mike",
    whatHappened:
      "The first thermonuclear device was tested at Enewetak Atoll on 31 October 1952.",
    whyItMattered:
      "It proved fusion's enormous energy release was achievable on Earth — but only as a single, uncontrolled explosive burst, not a usable power source.",
  },
  {
    id: "z-pinch",
    year: "1950s",
    title: "Z-pinch",
    whatHappened:
      "Scientists tried confining plasma using the magnetic field generated by an electric current running through it.",
    whyItMattered:
      "It was one of the first real attempts at controlled fusion — and its instability problems taught researchers how difficult confinement would actually be.",
  },
  {
    id: "t1-tokamak",
    year: "1958",
    title: "T-1 tokamak",
    whatHappened:
      "Soviet researchers operated the T-1 device, generally considered the first tokamak — a toroidal (donut-shaped) magnetic confinement design.",
    whyItMattered:
      "The tokamak became one of the leading approaches to magnetic confinement and later became the design basis for major fusion projects, including ITER.",
  },
  {
    id: "today",
    year: "Today",
    title: "Modern fusion research",
    whatHappened: "Fusion research continues at facilities like ITER and NIF, and at private fusion companies.",
    whyItMattered:
      "This is where Module 5 picks up the story — see \"The Fusion Race\" to find out where things stand right now.",
  },
];
